### ISSUE TITLE
Add env variable for HDF5 support

### ISSUE THREAD

**Issue by gdhugo** [gdhugo/coral_singularity#1]
```
Traceback (most recent call last):
  File "/home/ghugo/code/ticker/ticker/train.py", line 121, in <module>
    process(configuration)
  File "/home/ghugo/code/ticker/ticker/train.py", line 52, in process
    model = Model_Factory().make(cf, optimizer)
  File "/home/ghugo/code/ticker/ticker/network/models/model_factory.py", line 46, in make
    optimizer)
  File "/home/ghugo/code/ticker/ticker/network/models/model_factory.py", line 62, in make_one_net_model
    classes=cf.classes)
  File "/home/ghugo/code/ticker/ticker/network/models/models.py", line 231, in AtrousFCN_Resnet50_16s
    model.load_weights(weights_path, by_name=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1538, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented')
```

This issue is solved with:
`export HDF5_USE_FILE_LOCKING='FALSE'`

this environment variable needs to be added to the Singularity build recipes for TF 1.12.

**Comment by gdhugo** [comment]
Fixed in last commit.
